relativeURLs = true
title = "Dr. Himani Arora"
theme = ["academimal"]
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml", "make.sh" ]

enableEmoji = true
enableGitInfo = true
canonifyURLs = true
enableRobotsTXT = true


[params]
	author = "Dr. Himani Arora"
	sitename = "Personal website of Dr. Himani Arora"
    logo = "himani-arora-profile.jpeg" 
    shortbio = "Ph.D. in Applied Physics"
    shortbio2 = "2 years of Postdoc experience"
    shortbio3 = "ultra-thin semiconductors | 2D Materials |  nanoelectronics | opto-electronics"
    
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  

