relativeURLs = true
title = "Dr. Himani Arora"
theme = ["academimal"]
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]
[params]
    logo = "himani-arora-profile.jpeg" 
    shortbio = "Ph.D. in Applied Physics         2D materials | photodetectors | electronic characterization "
    
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  

